import type { Metadata } from 'next'
import '../ui/globals.css'
import { montserrat, roboto } from '../ui/fonts'
import { Header } from '@/ui/mainNav/Header'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${roboto} ${montserrat} antialiased`}>
                <Header />
                <div>{children}</div>
                <aside></aside>
            </body>
        </html>
    )
}
