import type { Metadata } from 'next'
import '../ui/globals.css'
import { montserrat, roboto } from '../ui/fonts'
import HeaderServer from '@/ui/mainNav/HeaderServer'
// import ToastNotification from '@/ui/ToastNotification'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${roboto} ${montserrat} antialiased`}>
                <HeaderServer />
                <div>{children}</div>
                <aside></aside>
                {/* <ToastNotification /> */}
            </body>
        </html>
    )
}
