import type { Metadata } from 'next'
import { Nav } from '@/components/ui/mainNav/Nav';
import { montserrat, roboto } from '@/ui/fonts';

interface Category {
    id: number;
    nombre: string;
}

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    categories,
}: Readonly<{
    children: React.ReactNode;
    categories: Category[];
}>) {
    return (
        <html lang="en">
            <body className={`${roboto} ${montserrat} antialiased`}>
                <Nav categories={categories} />
                <main className='mt-30'>{children}</main>
            </body>
        </html>
    )
}
